"""love_dates added

Revision ID: 32c5d36947e8
Revises: b4ea5ebc9b6d
Create Date: 2024-07-10 00:43:22.075377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32c5d36947e8'
down_revision = 'b4ea5ebc9b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couples', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    with op.batch_alter_table('lovestory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_meet_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('first_date_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('proposal_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('engagement_date', sa.Date(), nullable=False))

    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('lovestory', schema=None) as batch_op:
        batch_op.drop_column('engagement_date')
        batch_op.drop_column('proposal_date')
        batch_op.drop_column('first_date_date')
        batch_op.drop_column('first_meet_date')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('couples', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
