"""add couples table

Revision ID: 34b97d80c917
Revises: 67e54334329b
Create Date: 2024-06-17 00:16:03.975087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34b97d80c917'
down_revision = '67e54334329b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('qualification', sa.String(length=80), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('relative1', sa.String(length=80), nullable=False),
    sa.Column('relation1', sa.String(length=80), nullable=False),
    sa.Column('relative2', sa.String(length=80), nullable=False),
    sa.Column('relation2', sa.String(length=80), nullable=False),
    sa.Column('relative3', sa.String(length=80), nullable=False),
    sa.Column('relation3', sa.String(length=80), nullable=False),
    sa.Column('groom_bride', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    op.drop_table('couples')
    # ### end Alembic commands ###
