"""add place

Revision ID: 67e54334329b
Revises: 815be1201ff0
Create Date: 2024-06-16 23:43:33.820351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67e54334329b'
down_revision = '815be1201ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', sa.String(length=80), nullable=False))
        batch_op.drop_column('groom_name')
        batch_op.drop_column('bride_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bride_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('groom_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('place')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
