"""add couples table image

Revision ID: b3b861e9d783
Revises: 34b97d80c917
Create Date: 2024-06-17 00:50:01.485291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b861e9d783'
down_revision = '34b97d80c917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(length=4294967295), nullable=False))

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('couples', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
